INPUT:
  HEIGHT: 384
  WIDTH: 128
MODEL:
  GPUID: 7
  BN_LAYER: True
  EMBEDDING_SIZE: 1024
  LOSS:
    INSTANCE: 1.0
    GLOBALALIGN: 0.0
    CMPC: 0.0
    CMPM: 0.0
    MH: 1.0
  VISUAL_MODEL:
    NAME: 'resnet50' #['PCB', 'resnet50']
    NUM_STRIPES: 6
  TEXTUAL_MODEL:
    NAME: 'bilstm'
    MAX_LENGTH: 80
    EMBEDDING_SIZE: 768
    HIDDEN_SIZE: 512
    DROPOUT: 0.0
    BIDIRECTION: True
    NUM_LAYERS: 1
    ATN_LAYERS: ''
    WORDS: True
SOLVER:
  BATCH_SIZE: 64
  NUM_EPOCHES: 60
  BASE_LR: 0.0001 #0.0001
  WEIGHT_DECAY: 0.00004
  LRSCHEDULER: 'step'
  STEPS: (40, 55) #(40, 70)
  WARMUP_FACTOR: 0.1 #0.1
  WARMUP_EPOCHS: 5 #5
TEST:
  BATCH_SIZE: 64